### ISSUE TITLE
Need some help.

### ISSUE THREAD

**Issue by MrYoshii** [Krey81/Storj#3]
Hi sry for using issues for this but im only getting this.

`Storj3Monitor script by Krey ver 0.7.4
mail-to: krey@irinium.ru

I work on beer. If you like my scripts please donate bottle of beer in STORJ or ETH to 0x7df3157909face2dd972019d590adba65d83b1d8
Why should I send bootles if everything works like that ?
... see TODO comments in the script body

Thanks Sans Kokor for bug hunting
Thanks underflow17

Latest storagenode version is 0.33.4, query time 0ms`

**Comment by Krey81** [comment]
Hello.
You need to fill config file and give it path to script.
Config examples on github.
If any issues later, ask me.


21 февр. 2020 г. 22:04 пользователь MrYoshii <notifications@github.com> написал:

Hi sry for using issues for this but im only getting this.

`Storj3Monitor script by Krey ver 0.7.4
mail-to: krey@irinium.ru<mailto:krey@irinium.ru>

I work on beer. If you like my scripts please donate bottle of beer in STORJ or ETH to 0x7df3157909face2dd972019d590adba65d83b1d8
Why should I send bootles if everything works like that ?
... see TODO comments in the script body

Thanks Sans Kokor for bug hunting
Thanks underflow17

Latest storagenode version is 0.33.4, query time 0ms`
